### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by erwer8363** [GeeTeam/gt4_flutter_plugin#1]
从pup上下载下来的插件，总是报flutter: Captcha onError: {desc: {time: 2022-04-28 18:43:55, exce_desc: Missed resource: gt4-index.html, error_code: -20002, os_version: 14.4, client_type: ios, device_type: x86_64, sdk_version: 1.7.2}, code: -20002}这个错误。但是运行example文件就行。不知道哪里的原因，大佬看到了，能否指导一下？

**Comment by Liberations** [comment]
我遇到了 要导入bundle GTCaptcha4.bundle

**Comment by erwer8363** [comment]
> 

导入到哪里，我导入了也是报这个错。。不论是放到插件里，还是在xcode里导入。都是这个错。。

**Comment by NikoXu** [comment]
> > 
> 
> 导入到哪里，我导入了也是报这个错。。不论是放到插件里，还是在xcode里导入。都是这个错。。

```
/** Android 主程序的 libs 路径(Android main project libs path) */
example/android/app/libs

/** iOS Flutter 插件(iOS Flutter plugin path) */
ios/Libraries/*
```

**Comment by erwer8363** [comment]
> > > 
> > 
> > 
> > 导入到哪里，我导入了也是报这个错。。不论是放到插件里，还是在xcode里导入。都是这个错。。
> 
> ```
> /** Android 主程序的 libs 路径(Android main project libs path) */
> example/android/app/libs
> 
> /** iOS Flutter 插件(iOS Flutter plugin path) */
> ios/Libraries/*
> ```

**Comment by erwer8363** [comment]
ios/Libraries/*   这个目录是建立在那里，是在项目下的ios下面建立libraries文件夹还是在flutter plugin下面的 gt4 下面的 ios先建立？ 我两个地方都试了还不行，
