### ISSUE TITLE
完全按照文档说明，xcode也导入资源了，仍然报错资源找不到

### ISSUE THREAD

**Issue by junixapp** [GeeTeam/gt4_flutter_plugin#11]
| Geetest 4.0 | Flutter | onError:Closure: (Map<String, dynamic>) => Future<Null>
flutter: Captcha onError: {msg: (null) (-20002), desc: {time: 2023-07-26 16:24:29, exce_desc: Missed resource: gt4-index.html, error_code: -20002, os_version: 16.2, client_type: ios, device_type: x86_64, sdk_version: 1.8.2}, code: -20002}

**Comment by chupengfeiGeetest** [comment]
您好，该问题是缺少了中间页资源文件，您如果已经导入了看看目录是否正确，有问题继续联系，谢谢
