### ISSUE TITLE
0.0.8版本，运行报错找不到gt4-index.html

### ISSUE THREAD

**Issue by junixapp** [GeeTeam/gt4_flutter_plugin#12]
Captcha onError: {msg: (null) (-20002), desc: {time: 2023-08-18 18:03:25, exce_desc: Missed resource: gt4-index.html, error_code: -20002, os_version: 16.2, client_type: ios, device_type: x86_64, sdk_version: 1.8.2}, code: -20002}

**Comment by junixapp** [comment]
仍然需要手动导入GTCaptcha4.bundle资源，否则还是报错找不到

**Comment by sunnyGeetest** [comment]
插件从 0.0.8 版本开始无需手动导入SDK，但 iOS 因资源引用问题，仍需手动将 GTCaptcha4.bundle 拖入 Xcode
