### ISSUE TITLE
Android. Namespace not specified

### ISSUE THREAD

**Issue by ne3Vubeki** [GeeTeam/gt4_flutter_plugin#14]
When synchronizing a project with gradle files, an error occurs in your plugin:

```
A problem occurred configuring project ':gt4_flutter_plugin'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
```

flutter 3.24.4

**Comment by ccBiver** [comment]
Find gt4_flutter_plugin-0.1.1 in Flutter Plugins in External Libraries, click build.gradle in the android directory, add namespace "com.geetest.captcha.flutter.gt4_flutter_plugin" in android{}, and delete package="com.geetest.captcha.flutter.gt4_flutter_plugin" in AndroidManifest.
