### ISSUE TITLE
资源缺失

### ISSUE THREAD

**Issue by erwer8363** [GeeTeam/gt4_flutter_plugin#2]
ios，按照提示一步一步添加到，结果总是报-20002， 查错误码说是资源缺失，我已经吧bundle和framework全都放到libraries下面了，

**Comment by KhaleelSH** [comment]
@erwer8363 The solution to this is to add the .bundle and .framework in the plugin ios library. AND to add .bundle to your project ios folder using xCode.
This plugin needs a lot of improvement.

**Comment by sunnyGeetest** [comment]
插件 0.0.7 版本开始支持远程依赖原生SDK，无需手动添加，但 iOS 因资源引用问题仍需手动将 GTCaptcha4.bundle 拖入到 Xcode

**Comment by sunnyGeetest** [comment]
插件 0.0.7 版本开始支持远程依赖原生SDK，无需手动添加，但 iOS 因资源引用问题仍需手动将 GTCaptcha4.bundle 拖入到 Xcode
