### ISSUE TITLE
[Plugin not work in iOS] Swift Compiler Error (Xcode): Module 'GTCaptcha4' not found

### ISSUE THREAD

**Issue by theideasaler** [GeeTeam/gt4_flutter_plugin#3]
Hi, I have followed the official instruction. Everything works fine in Android, but the iOS failed to build.

Bundle imported:
![image](https://user-images.githubusercontent.com/17869748/189787792-79421de6-0e77-48f9-b4ca-6635c0f4b580.png)

Linker
![image](https://user-images.githubusercontent.com/17869748/189788093-892895f3-fd94-4b2a-84d3-4c58df8abc02.png)

Folder structure
<img width="596" alt="image" src="https://user-images.githubusercontent.com/17869748/189788131-84646cbe-eaae-41e5-a69b-0210b84e5276.png">

But I still get this error:

```
Swift Compiler Error (Xcode): Module 'GTCaptcha4' not found
/Users/neo/Desktop/my_project/flutter/.pub-cache/hosted/pub.dartlang.org/gt4_flutter_plugin-0.0.3/ios/Classes/Gt4FlutterPlugin.h:2:8
```

which points to this file:
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/17869748/189788306-e7866989-23f4-4d6d-9f96-5cdc1f146121.png">

Could you please suggest if I missed something?

**Comment by NikoXu** [comment]
Hello, @theideasaler 

The iOS SDK should be imported to `ios/Libraries`.

https://github.com/GeeTeam/gt4_flutter_plugin/tree/master/ios/Libraries

**Comment by theideasaler** [comment]
thanks, I can confirm this do fix the issue.
