### ISSUE TITLE
安卓运行错误

### ISSUE THREAD

**Issue by steveyu2** [GeeTeam/gt4_flutter_plugin#4]
![image](https://user-images.githubusercontent.com/26341956/218641185-e8bc9d06-0b13-46dc-9cb7-67ad9e51cbbe.png)

**Comment by CRXGeeTest** [comment]
我们发布了0.0.6版本, 更新了 `fluttertoast` 依赖, 麻烦您看下是否还会运行错误

**Comment by steveyu2** [comment]
更新flutter 3.7+解决了
