### ISSUE TITLE
错误：什么原因

### ISSUE THREAD

**Issue by Wellcomezhangheng** [GeeTeam/gt4_flutter_plugin#6]
{msg: The web content process is terminated., desc: {time: 2023-05-10 13:58:41, exce_desc: The web view’s web content process is terminated. The white screen coming soon. Maybe there are insufficient memory for the web content process., error_code: -20290, message: The web content process is terminated., client_type: ios, os_version: 15.4.1, device_type: iPhone13,2, sdk_version: 1.8.1}, code: -20290}

**Comment by sunnyGeetest** [comment]
The reason for error -20290 is receiving a memory warning in the WebView, causing the system to call the webViewWebContentProcessDidTerminate: delegate method.

**Comment by sunnyGeetest** [comment]
The reason for error -20290 is receiving a memory warning in the WebView, causing the system to call the webViewWebContentProcessDidTerminate: delegate method.
