### ISSUE TITLE
Android Captcha.close() throws method invocation failed exception

### ISSUE THREAD

**Issue by phillip-dev-pcap** [GeeTeam/gt4_flutter_plugin#7]
Flutter Geetest library version : 0.0.7
Android library version : 1.8.2
Root Cause : No method definition found for captcha.close()

When analyzing the plugin code, there is no method definition found for the captcha.close().

    override fun onMethodCall(@NonNull call: MethodCall, @NonNull result: Result) {        
    when (call.method) {
            "initWithCaptcha" -> {
                initWithCaptcha(activity!!, call.arguments)
            }
            "verify" -> {
                verifyWithCaptcha()
            }
            "configurationChanged" -> {
                configurationChanged(Configuration())
            }
            "getPlatformVersion" -> {
                result.success(GTCaptcha4Client.getVersion())
            }
            else -> {
                result.notImplemented()
            }
        }
    }

Please help to resolve this.

**Comment by sunnyGeetest** [comment]
We have fixed this issue in version 0.0.9 of the plugin. Please upgrade to the latest version.
