### ISSUE TITLE
language

### ISSUE THREAD

**Issue by LvDj** [GeeTeam/gt4_flutter_plugin#8]
language = "kor";
Language is invalid. Only Chinese and English can be set

**Comment by sunnyGeetest** [comment]
The SDK language is divided into prompt text and captcha interface text. The prompt text is natively localized and supports only Chinese and English. The captcha interface text supports multiple languages and requires passing parameters to the SDK, which will be controlled by the frontend.

**Comment by sunnyGeetest** [comment]
The SDK language is divided into prompt text and captcha interface text. The prompt text is natively localized and supports only Chinese and English. The captcha interface text supports multiple languages and requires passing parameters to the SDK, which will be controlled by the frontend.
